# This script is for extracting the contig list in the two major branches of delineaged bins generated by second clustering
# module load Biopython
import os
from Bio import Phylo

# Directory containing the Newick files
directory = "/path/to/newick/files"

# Process each Newick file in the directory
for filename in os.listdir(directory):
    if filename.endswith(".newick"):
        # Read the Newick tree from the file
        filepath = os.path.join(directory, filename)
        tree = Phylo.read(filepath, "newick")

        # Get the root of the tree
        root = tree.root

        # Get the two major branches (children of the root)
        major_branches = root.clades[:2]

        # Extract the contig IDs from each major branch
        branch_ids = []
        for branch in major_branches:
            ids = [clade.name for clade in branch.get_terminals()]
            branch_ids.append(ids)

        # Write the contig ID lists to separate files
        clusterA_file = os.path.join(directory, f"{filename}_clusterA.list")
        clusterB_file = os.path.join(directory, f"{filename}_clusterB.list")

        with open(clusterA_file, "w") as f:
            f.write("\n".join(branch_ids[0]))

        with open(clusterB_file, "w") as f:
            f.write("\n".join(branch_ids[1]))

        print(f"Processed: {filename}")
